version: '3'
services:
  maven-repo:
    image: sonatype/nexus3
    ports:
     - "8089:8081"
    volumes:
       - /Users/pezhang/docker/nexus-data:/nexus-data
networks:
  default:
    external:
      name: my_pipeline
