pipeline {
    agent any

    stages {
        stage('start maven repo') {
            steps {
                sh 'docker-compose -f ./assembly/docker/docker-compose.yml up -d'
            }
        }

        stage('provider integration test') {
            agent {
                docker {
                    image 'java:8'
                    label 'provider'
                    args  '-v /Users/pezhang/Demo/spring-cloud/spring-cloud-contract-demo/provider-service:/var/app/provider-service'
                    reuseNode true
                }
            }

            steps {
                sh 'cd /var/app/provider-service && ./gradlew clean test'
            }
        }

        stage('provider publish') {
            steps {
                sh 'cd /var/app/provider-service && ./gradlew clean test'
            }
        }
    }

    post {
        always {
            echo 'This will always run'
            deleteDir()
        }

        success {
            echo 'This will run only if successful'
        }

        failure {
            echo 'This will run only if failed'
        }

        unstable {
            echo 'This will run only if the run was marked as unstable'
        }

        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}